{% set name = "sk-video" %}
{% set version = "1.1.10" %}
{% set sha256 = "fb7125cfa2b31253dcf181d0bf285edd6bb25ffebf61dbd8ba11fadb783609a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - skvideo
    - skvideo.io
    - skvideo.motion
    - skvideo.measure
    - skvideo.datasets
    - skvideo.utils

about:
  home: https://github.com/scikit-video/scikit-video
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Video Processing in Python'

  description: |
    scikit-video is a Python module for video processing
    built on top of scipy, numpy, and ffmpeg/libav
  doc_url: http://www.scikit-video.org/
  dev_url: https://github.com/scikit-video/scikit-video

extra:
  recipe-maintainers:
    - carlodri
